name: Build and Upload JPEGView

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-win32:
    name: Build Win32 Release
    uses: ./.github/workflows/workflow-build-wtl-submodule.yml
    with:
      platform-arch: Win32
      build-config: Release

  build-x64:
    name: Build x64 Release
    uses: ./.github/workflows/workflow-build-wtl-submodule.yml
    with:
      platform-arch: x64
      build-config: Release
